version: '1.0'
name: hexo-pipeline
displayName: hexo-pipeline
stages:
  - stage: ''
    name: stage_1
    displayName: stage_display_1
    steps:
      - step: build@nodejs
        name: build_nodejs_68
        displayName: Nodejs 构建
        nodeVersion: 10.17.0
        failFast: true
        commands:
          - node -v
          - npm -v
          - chmod 777 qshell
          - ls -l
          - export PATH=$PATH:$(echo `pwd`)
          - qshell -v
          - qshell account $Nxn5B9kW1_y0na5zCRWnfmLwiFRrKw894l-yDs8k $ZxCmaRJRl9zkfkW6BXY2ZBKoFsAJqLItEhXkYQXK gybbs123@foxmail.com
          - qshell user ls
          - sed -i "s:file_path:$(echo "`pwd`/public"):" upload-giteego.conf
          - cat upload-giteego.conf
          - npm install
          - npm run giteePush
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
      include:
        - master
